### ISSUE TITLE
TODO: Proposed API & Packaging Improvements (+ Planned Breaking Changes)

### ISSUE THREAD

**Issue by lamarrr** [lamarrr/STX#33]
- [x] rename and separate config.h into stx_cfg_utils as users might think they need to modify the config header file to use STX
- [x] Make `Option` and `Result`‘s `value` and `error` methods conform to the C++ object model and use references.
- [x] Document exception guarantees 
- [x] `Some`, `Ok`, and `Err` are value forwarders, hence, they shouldn’t have any other method or operations  whatsoever, even copy.
- [x] Make the methods external to `Result` and `Option` and support const references, l-value references, and r-value references.
- [x] Separate `Option` and `Result` and use helper functions to resolve the tight dependencies. (stx_option, stx_result). This would also enable us to use SFINAE to dispatch methods where necessary without too much code.
- [x] Separate panic features into separate stx_panic package, there should be no dependency on non-STX packages by default.
- [x] Evaluate if panic could benefit from branch guiding i.e. `[[unlikely]]`
- [x] Report should also be under the panic package
- [x] Separate panic implementations (stx_panic_halt, stx_panic_abort, etc.)
- [x] add stx_panic_pretty_stacktraced package
- [x] Make panic always use an injectable function pointer (hooks) since it’s always in the cold path and panics should only happen once before permanent termination.
- [x] Let the user customize panic behavior at runtime ***only*** and not via cmake config which is already confusing.
- [x] Make `Option` and `Result` actually use `std::invoke`
- [x] reduce and streamline methods in `Option` and `Result` to make it easier to maintain and extend (i.e. redundant methods like most Option::*). 
- [x] [TOP PRIORITY]  add specialization for `Result<void, Error>`
- [x] Replace mutexes with a custom hybrid spin lock  implementation as embedded systems don’t support it
- [x] Consider using fmt or fmt-style interface for panics. It should be allowed to use dynamic memory 
- [x] Remove static methods in `Span` and make them helper functions instead.
- [x] Replace `SpanReport` and `FixedReport` with better and safe alternatives, consider:
- [x] add default reporters for enum types. By just casting to the enum’s underlying type. I’ve found it quite tedious implementing reporters for each enum type for each API I’m using. Sometimes I’m satisfied with integers.
- [x] let `Option` and `Result` be constexpr for constexprable trivial types
- [x] Explore other light-weight and portable alternatives to absl’s backtrace which is quite heavy and slows down our build at the moment
- [x] Remove all noexcept statements and defaulted constructors and operators (See: https://github.com/lamarrr/STX/issues/31)
- [x] Move option and result comparison operations outside of the structures and to a separate header
- [x] Verify and add tests for panic hooks if possible 
- [x] Simplify and rewrite CMake File
- [x] Change documentation solution
- [x] Draft tutorials
- [x] Clean up and publish the internally developed async and task library (could help @Invander29 https://github.com/lamarrr/STX/issues/9)
- [x] Publish the remaining internally used utilities (enums, struct, limits, etc).
- [x] Logo and brand change
- [x] Remove coroutine macros
- [x] SFINAE macros + header
- [x] Option and Result SFINAE support? I’m not convinced this is important
- [x] Allow projects to inject namespaces or symbol overrides (I.e. where there are multiple or same STX versions packaged differently).
- [x] stx_mem stx_res stx_limits stx_enum
- [x] Add clang format file + CI check  (https://github.com/lamarrr/STX/issues/27)
- [x] Add more ARM and embedded systems CI tests
- [x] remove libatomic auto linking ```find_library(LibAtomic atomic)```
- [x] remove `TRY_OK` and `TRY_SOME` and replace with `STX_TRY`?
- [x] rename `CFG` to `STX_CFG`?
- [x] a number of `const&` are unnecessary since the types are cheap to copy
- [x] add CI examples building
- [x] add CI clang format checks
- [x] consider making Result and Option's destructive methods (I.e. Methods that move out the value) allow l-value references

**Comment by athanase** [comment]
Hello, 

>  [TOP PRIORITY] add specialization for Result<void, Error>

is marked as done, is this already in the repo somewhere ?

Thanks in advance.

**Comment by lamarrr** [comment]
> Hello,
> 
> > [TOP PRIORITY] add specialization for Result<void, Error>
> 
> is marked as done, is this already in the repo somewhere ?
> 
> Thanks in advance.

Hi, it was up for consideration but I decided not to implement it because it would lead to a lot of code repetition and high maintenance burden for little gain

**Comment by athanase** [comment]
I understand. There is currently no way in STX to write the following snippet other that specializing `Result<void, Error>`, right?

```
stx::Result<Error> foo::bar()
{
    if( failing )
    {
        return stx::Err( Error::some_error );
    }
    return stx::Ok();
}
```

I am asking this because when using STX's approach to error handling I think it is a good thing to use it for this specific use case as well.

**Comment by lamarrr** [comment]
Sadly, yeah. There is no way to do that.

You can define a regular void type and do:

```cpp
struct Void{};

stx::Result<Void, Error> foo::bar()
{
    if( failing )
    {
        return stx::Err( Error::some_error );
    }
    return stx::Ok<Void>();
}

```
